
openapi: 3.0.3
info:
  title: Wallet management
  version: 1.0.1
  description: This spec manages wallet created by STD22057 and STD22006
servers:
  - url: https://management.wallet
tags:
  - name: Account
  - name: Transaction
paths:
  /accounts:
    get:
      tags:
        - Account
      summary: Get all Accounts
      description: Return all accounts
      operationId: getAllAccounts
      responses:
        '200':
          description: Successful retrieval of account data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '500':
          description: Internal server error
    put:
      tags:
        - Account
      summary: Create or update an or a list of account
      description: Create if the account does not exists, otherwise update it
      operationId: crupdateAccounts
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - type: array
                  items:
                    $ref: '#/components/schemas/Account'
                - $ref: '#/components/schemas/Account'
      responses:
        '200':
          description: Account created or updated successfully
          content:
            application/json:
              schema:
                oneOf:
                  - type: array
                    items:
                      $ref: '#/components/schemas/Account'
                  - $ref: '#/components/schemas/Account'
        '400':
          description: Bad or invalid request
        '500':
          description: Internal server error
  /accounts/{id}:
    get:
      tags:
        - Account
      summary: Get account by ID
      description: Return details of a specific account
      operationId: getAccountById
      parameters:
        - in: path
          name: id
          description: The ID of the account to retrieve
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful retrieval of account data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '404':
          description: Account not found or does not exists
        '505':
          description: Internal server error
  /transactions:
    get:
      tags:
        - Transaction
      summary: Get all transactions
      description: Return all transactions
      operationId: getAllTransactions
      responses:
        '200':
          description: Successful retrieval of transaction data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '500':
          description: Internal server error
    put:
      tags:
        - Transaction
      summary: Create or update a or a list of transaction
      description: Create if the transaction does not exists, otherwise update it
      operationId: crupdateTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - type: array
                  items:
                    $ref: '#/components/schemas/Transaction'
                - $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          description: Transaction created or updated successfully
          content:
            application/json:
              schema:
                oneOf:
                  - type: array
                    items:
                      $ref: '#/components/schemas/Transaction'
                  - $ref: '#/components/schemas/Transaction'
        '400':
          description: Bad or invalid request
        '500':
          description: Internal server error
  /transactions/{id}:
    get:
      tags:
        - Transaction
      summary: Get transaction by ID
      description: Return details of a specific transaction
      operationId: getTransactionById
      parameters:
        - in: path
          name: id
          description: The ID of the transaction to retrieve
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful retrieval of transaction data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '404':
          description: Transaction not found or does not exists
        '505':
          description: Internal server error
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        currency:
          type: string
        balance:
          type: number
          format: double
    Transaction:
      type: object
      properties:
        id:
          type: integer
        description:
          type: string
        amount:
          type: number
          format: double
        type:
          type: string
        correspondent:
          type: string